// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Perla_AP2_API_20190008.DAL;

namespace Perla_AP2_API_20190008.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211110190926_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Perla_AP2_API_20190008.Entidades.Articulos", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Inventario")
                        .HasColumnType("TEXT");

                    b.HasKey("ArticuloId");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            ArticuloId = 1,
                            Costo = 0m,
                            Descripcion = "Caja de avena",
                            Inventario = 0m
                        },
                        new
                        {
                            ArticuloId = 2,
                            Costo = 0m,
                            Descripcion = "Faldos de refrescos",
                            Inventario = 0m
                        },
                        new
                        {
                            ArticuloId = 3,
                            Costo = 0m,
                            Descripcion = "Cajas de sopa",
                            Inventario = 0m
                        },
                        new
                        {
                            ArticuloId = 4,
                            Costo = 0m,
                            Descripcion = "Embutidos",
                            Inventario = 0m
                        },
                        new
                        {
                            ArticuloId = 5,
                            Costo = 0m,
                            Descripcion = "Cajas de jabones",
                            Inventario = 0m
                        });
                });

            modelBuilder.Entity("Perla_AP2_API_20190008.Entidades.Proveedores", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            ProveedorId = 1,
                            Nombre = "Bodega de Jesus"
                        },
                        new
                        {
                            ProveedorId = 2,
                            Nombre = "Bodega Rodriguez"
                        },
                        new
                        {
                            ProveedorId = 3,
                            Nombre = "Supermercado Suarez"
                        },
                        new
                        {
                            ProveedorId = 4,
                            Nombre = "Supermercado Canario"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
